import {
  API_URL,
  API_ACCESS_TOKEN,
  API_URL_RECOMEND,
  API_URL_SEARCH_KEYWORD,
  include,
  API_URL_GENRE_LIST,
  API_URL_SEARCH_MOVIE_BY_GENRE,
} from "@env";

export default {
  API_URL,
  API_ACCESS_TOKEN,
  API_URL_RECOMEND,
  API_URL_SEARCH_KEYWORD,
  include,
  API_URL_GENRE_LIST,
  API_URL_SEARCH_MOVIE_BY_GENRE,
};
